import type { Metadata } from 'next';
import localFont from 'next/font/local';
import cl from 'classnames';

import { AppProvider } from '@/common/AppProvider';
import { AppLayout } from '@/common/components/layouts/AppLayout';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-screen overflow-hidden" lang="en">
      <body
        className={cl(
          'h-screen overflow-hidden relative overflow-hidden text-white',
          geistSans.variable,
          geistMono.variable,
          'antialiased',
        )}
      >
        <AppProvider>
          <AppLayout>{children}</AppLayout>
        </AppProvider>
      </body>
    </html>
  );
}
